export const GameData = [

    {
        game_id: "pokemon-brilliant-diamond", 
        game_title: "Pokémon Brilliant Diamond", 
        release_date: '2021-11-19', 
        preorder_date:'', 
        developer:'ILCA',
        publisher:'Nintendo',
        hype:'0',
        msrp:'$59.99',
        amazon_link:'',
        target_link:'',
        nintendo_eshop_link:'',
        steam_link:'',
        kickstarter_link:'',
        is_physical:'1',
        is_digital:'1',
        img_self_link: 'https://assets.nintendo.com/image/upload/c_pad,f_auto,h_613,q_auto,w_1089/ncom/en_US/games/switch/p/pokemon-brilliant-diamond-switch/hero?v=2021052619', 
        banner_img_self_link: 'https://assets.nintendo.com/image/upload/c_pad,f_auto,h_613,q_auto,w_1089/ncom/en_US/games/switch/p/pokemon-brilliant-diamond-switch/hero?v=2021052619',
        switch_img_self_link: 'https://diamondpearl.pokemon.com/assets/img/global/en-us/packshot-d-2x.png',
        ps5_img_self_link:'',
        ps4_img_self_link:'',
        xbox_img_self_link:'',
        platforms: ["Switch"],
        screenshot_self_links:'[]',
        coverage_links:'[]'
    },
    

    {
        game_title: "Pokémon Legend Arceus", 
        release_date: '2021-11-19', 
        preorder_date:'', 
        developer:'Game Freak',
        publisher:'Nintendo',
        hype:'0',
        msrp:'$59.99',
        amazon_link:'',
        target_link:'',
        nintendo_eshop_link:'',
        steam_link:'',
        kickstarter_link:'',
        is_physical:'1',
        is_digital:'1',
        img_self_link: 'https://assets.nintendo.com/image/upload/c_pad,f_auto,h_613,q_auto,w_1089/ncom/en_US/games/switch/p/pokemon-brilliant-diamond-switch/hero?v=2021052619', 
        banner_img_self_link: 'https://assets.nintendo.com/image/upload/c_pad,f_auto,h_613,q_auto,w_1089/ncom/en_US/games/switch/p/pokemon-brilliant-diamond-switch/hero?v=2021052619',
        switch_img_self_link: 'https://diamondpearl.pokemon.com/assets/img/global/en-us/packshot-d-2x.png',
        ps5_img_self_link:'',
        ps4_img_self_link:'',
        xbox_img_self_link:'',
        platforms: ["Switch"],
        screenshot_self_links:'[]',
        coverage_links:'[]'
    },
    {
        game_title: "Pokémon Legend Arceus", 
        release_date: '2021-11-19', 
        preorder_date:'', 
        developer:'Game Freak',
        publisher:'Nintendo',
        hype:'0',
        msrp:'$59.99',
        amazon_link:'',
        target_link:'',
        nintendo_eshop_link:'',
        steam_link:'',
        kickstarter_link:'',
        is_physical:'1',
        is_digital:'1',
        img_self_link: 'https://assets.nintendo.com/image/upload/c_pad,f_auto,h_613,q_auto,w_1089/ncom/en_US/games/switch/p/pokemon-brilliant-diamond-switch/hero?v=2021052619', 
        banner_img_self_link: 'https://assets.nintendo.com/image/upload/c_pad,f_auto,h_613,q_auto,w_1089/ncom/en_US/games/switch/p/pokemon-brilliant-diamond-switch/hero?v=2021052619',
        switch_img_self_link: 'https://diamondpearl.pokemon.com/assets/img/global/en-us/packshot-d-2x.png',
        ps5_img_self_link:'',
        ps4_img_self_link:'',
        xbox_img_self_link:'',
        platforms: ["Switch"],
        screenshot_self_links:'[]',
        coverage_links:'[]'
    },
    

]