export const SummerGameFestKickOffData = [

{
    game_title: "Sable", 
    release_date: '2021-9-23', 
    preorder_date:'', 
    developer:'',
    publisher:'',
    hype:'0',
    msrp:'',
    amazon_link:'',
    target_link:'',
    nintendo_eshop_link:'',
    steam_link:'',
    kickstarter_link:'',
    is_physical:'0',
    is_digital:'1',
    img_self_link: 'GameImg/Sable/sable-shedworks.png', 
    banner_img_self_link: 'https://assets.nintendo.com/image/upload/c_pad,f_auto,h_613,q_auto,w_1089/ncom/en_US/games/switch/p/pokemon-brilliant-diamond-switch/hero?v=2021052619',
    switch_img_self_link: 'https://diamondpearl.pokemon.com/assets/img/global/en-us/packshot-d-2x.png',
    ps5_img_self_link:'',
    ps4_img_self_link:'',
    xbox_img_self_link:'',
    platforms: [""],
    screenshot_self_links:[""],
    coverage_links:'[]'
},

{
    game_title: "Elden Ring", 
    release_date: '2022-1-21', 
    preorder_date:'', 
    developer:'FromSoftware',
    publisher:'Bandai Namco',
    hype:'0',
    msrp:'$59.99',
    amazon_link:'',
    target_link:'',
    nintendo_eshop_link:'',
    steam_link:'',
    kickstarter_link:'',
    is_physical:'1',
    is_digital:'1',
    img_self_link: 'https://assets.nintendo.com/image/upload/c_pad,f_auto,h_613,q_auto,w_1089/ncom/en_US/games/switch/p/pokemon-brilliant-diamond-switch/hero?v=2021052619', 
    banner_img_self_link: 'https://assets.nintendo.com/image/upload/c_pad,f_auto,h_613,q_auto,w_1089/ncom/en_US/games/switch/p/pokemon-brilliant-diamond-switch/hero?v=2021052619',
    switch_img_self_link: 'https://diamondpearl.pokemon.com/assets/img/global/en-us/packshot-d-2x.png',
    ps5_img_self_link:'',
    ps4_img_self_link:'',
    xbox_img_self_link:'',
    platforms: ["PS4", "PS5", "XBO", "XBS"],
    screenshot_self_links:'[]',
    coverage_links:'[]'
},
{
    game_title: "Sky", 
    release_date: '2021-6-29', 
    preorder_date:'', 
    developer:'',
    publisher:'',
    hype:'0',
    msrp:'',
    amazon_link:'',
    target_link:'',
    nintendo_eshop_link:'',
    steam_link:'',
    kickstarter_link:'',
    is_physical:'1',
    is_digital:'1',
    img_self_link: 'https://assets.nintendo.com/image/upload/c_pad,f_auto,h_613,q_auto,w_1089/ncom/en_US/games/switch/p/pokemon-brilliant-diamond-switch/hero?v=2021052619', 
    banner_img_self_link: 'https://assets.nintendo.com/image/upload/c_pad,f_auto,h_613,q_auto,w_1089/ncom/en_US/games/switch/p/pokemon-brilliant-diamond-switch/hero?v=2021052619',
    switch_img_self_link: 'https://diamondpearl.pokemon.com/assets/img/global/en-us/packshot-d-2x.png',
    ps5_img_self_link:'',
    ps4_img_self_link:'',
    xbox_img_self_link:'',
    platforms: ["Switch"],
    screenshot_self_links:'[]',
    coverage_links:'[]'
},

]