export const WholesomeDirectData = [

    {
        game_title: "A Little To The Left", 
        release_date: '2021-10-21', 
        preorder_date:'', 
        developer:'Max Inferno',
        publisher:'Max Inferno',
        hype:'0',
        msrp:'',
        amazon_link:'',
        target_link:'',
        nintendo_eshop_link:'',
        PC_link:'https://store.PCpowered.com/app/1629520/A_Little_To_The_Left/',
        kickstarter_link:'',
        is_physical:'0',
        is_digital:'1',
        img_self_link: 'https://assets.nintendo.com/image/upload/c_pad,f_auto,h_613,q_auto,w_1089/ncom/en_US/games/switch/p/pokemon-brilliant-diamond-switch/hero?v=2021052619', 
        banner_img_self_link: '',
        switch_img_self_link: '',
        ps5_img_self_link:'',
        ps4_img_self_link:'',
        xbox_img_self_link:'',
        platforms: ["PC"],
        screenshot_self_links:'[]',
        coverage_links:'[]'
    },

    {
        game_title: "Alekon", 
        release_date: '2021-6-12', 
        preorder_date:'', 
        developer:'',
        publisher:'',
        hype:'0',
        msrp:'',
        amazon_link:'',
        target_link:'',
        nintendo_eshop_link:'',
        PC_link:'',
        kickstarter_link:'',
        is_physical:'0',
        is_digital:'1',
        img_self_link: '', 
        banner_img_self_link: '',
        switch_img_self_link: '',
        ps5_img_self_link:'',
        ps4_img_self_link:'',
        xbox_img_self_link:'',
        platforms: ["PC"],
        screenshot_self_links:'[]',
        coverage_links:'[]'
    },

    {
        game_title: "Lake", 
        release_date: '2021-9-1', 
        preorder_date:'', 
        developer:'',
        publisher:'',
        hype:'0',
        msrp:'',
        amazon_link:'',
        target_link:'',
        nintendo_eshop_link:'',
        PC_link:'',
        kickstarter_link:'',
        is_physical:'0',
        is_digital:'1',
        img_self_link: '', 
        banner_img_self_link: '',
        switch_img_self_link: '',
        ps5_img_self_link:'',
        ps4_img_self_link:'',
        xbox_img_self_link:'',
        platforms: ["PC"],
        screenshot_self_links:'[]',
        coverage_links:'[]'
    },

    {
        game_title: "Ooblets (0.8 Update)", 
        release_date: '2021-6-12', 
        preorder_date:'', 
        developer:'',
        publisher:'',
        hype:'0',
        msrp:'',
        amazon_link:'',
        target_link:'',
        nintendo_eshop_link:'',
        PC_link:'',
        kickstarter_link:'',
        is_physical:'0',
        is_digital:'1',
        img_self_link: '', 
        banner_img_self_link: '',
        switch_img_self_link: '',
        ps5_img_self_link:'',
        ps4_img_self_link:'',
        xbox_img_self_link:'',
        platforms: ["PC"],
        screenshot_self_links:'[]',
        coverage_links:'[]'
    },

    {
        game_title: "Beasts of Maravilla Island", 
        release_date: '2021-6-12', 
        preorder_date:'', 
        developer:'',
        publisher:'',
        hype:'0',
        msrp:'',
        amazon_link:'',
        target_link:'',
        nintendo_eshop_link:'',
        PC_link:'',
        kickstarter_link:'',
        is_physical:'0',
        is_digital:'1',
        img_self_link: '', 
        banner_img_self_link: '',
        switch_img_self_link: '',
        ps5_img_self_link:'',
        ps4_img_self_link:'',
        xbox_img_self_link:'',
        platforms: ["PC"],
        screenshot_self_links:'[]',
        coverage_links:'[]'
    },
    {
        game_title: "HOA", 
        release_date: '2021-8-21', 
        preorder_date:'', 
        developer:'',
        publisher:'',
        hype:'0',
        msrp:'',
        amazon_link:'',
        target_link:'',
        nintendo_eshop_link:'',
        PC_link:'',
        kickstarter_link:'',
        is_physical:'1',
        is_digital:'1',
        img_self_link: '', 
        banner_img_self_link: '',
        switch_img_self_link: '',
        ps5_img_self_link:'',
        ps4_img_self_link:'',
        xbox_img_self_link:'',
        platforms: ["PC", "Switch"],
        screenshot_self_links:'[]',
        coverage_links:'[]'
    },
    {
        game_title: "KeyWe", 
        release_date: '2021-8-31', 
        preorder_date:'', 
        developer:'',
        publisher:'',
        hype:'0',
        msrp:'',
        amazon_link:'',
        target_link:'',
        nintendo_eshop_link:'',
        PC_link:'',
        kickstarter_link:'',
        is_physical:'0',
        is_digital:'1',
        img_self_link: '', 
        banner_img_self_link: '',
        switch_img_self_link: '',
        ps5_img_self_link:'',
        ps4_img_self_link:'',
        xbox_img_self_link:'',
        platforms: ["PC"],
        screenshot_self_links:'[]',
        coverage_links:'[]'
    },
    {
        game_title: "Luna’s Fishing Garden", 
        release_date: '2021-10-21', 
        preorder_date:'', 
        developer:'',
        publisher:'',
        hype:'0',
        msrp:'',
        amazon_link:'',
        target_link:'',
        nintendo_eshop_link:'',
        PC_link:'',
        kickstarter_link:'',
        is_physical:'0',
        is_digital:'1',
        img_self_link: '', 
        banner_img_self_link: '',
        switch_img_self_link: '',
        ps5_img_self_link:'',
        ps4_img_self_link:'',
        xbox_img_self_link:'',
        platforms: ["PC"],
        screenshot_self_links:'[]',
        coverage_links:'[]'
    },
    {
        game_title: "Lego Builder’s Journey", 
        release_date: '2021-6-22', 
        preorder_date:'', 
        developer:'',
        publisher:'',
        hype:'0',
        msrp:'',
        amazon_link:'',
        target_link:'',
        nintendo_eshop_link:'',
        PC_link:'',
        kickstarter_link:'',
        is_physical:'0',
        is_digital:'1',
        img_self_link: '', 
        banner_img_self_link: '',
        switch_img_self_link: '',
        ps5_img_self_link:'',
        ps4_img_self_link:'',
        xbox_img_self_link:'',
        platforms: ["PC"],
        screenshot_self_links:'[]',
        coverage_links:'[]'
    },
    {
        game_title: "Powerwash Simulator", 
        release_date: '2021-6-12', 
        preorder_date:'', 
        developer:'',
        publisher:'',
        hype:'0',
        msrp:'',
        amazon_link:'',
        target_link:'',
        nintendo_eshop_link:'',
        PC_link:'',
        kickstarter_link:'',
        is_physical:'0',
        is_digital:'1',
        img_self_link: '', 
        banner_img_self_link: '',
        switch_img_self_link: '',
        ps5_img_self_link:'',
        ps4_img_self_link:'',
        xbox_img_self_link:'',
        platforms: ["PC"],
        screenshot_self_links:'[]',
        coverage_links:'[]'
    },
    {
        game_title: "Co-open", 
        release_date: '2021-6-12', 
        preorder_date:'', 
        developer:'',
        publisher:'',
        hype:'0',
        msrp:'',
        amazon_link:'',
        target_link:'',
        nintendo_eshop_link:'',
        PC_link:'',
        kickstarter_link:'',
        is_physical:'0',
        is_digital:'1',
        img_self_link: '', 
        banner_img_self_link: '',
        switch_img_self_link: '',
        ps5_img_self_link:'',
        ps4_img_self_link:'',
        xbox_img_self_link:'',
        platforms: ["PC"],
        screenshot_self_links:'[]',
        coverage_links:'[]'
    },


]