

// export const GameData = [

//     // game_title='Mario Golf: Super Rush', 
//     // release_date='2021-6-25',
//     // preorder_date='2021-6-25', 
//     // developer='Nintendo',
//     // hype='0',
//     // msrp='$59.99',
//     // amazon_link='https://www.amazon.com/Mario-Golf-Super-Rush-Nintendo-Switch/dp/B08WW82716',
//     // target_link='https://www.target.com/p/mario-golf-super-rush-nintendo-switch/-/A-82493760?ref=tgt_adv_XS000000&AFID=google_pla_df&fndsrc=tmnv&DFA=71700000079623000&CPNG=PLA_DVM%2B0060H00000uJmCNQA0-Nintendo_ExternalSearch_1H_Flight&adgroup=PLA_Nintendo&LID=700000001393753pgs&network=g&device=c&location=9032311&gclid=CjwKCAjwqvyFBhB7EiwAER786eIGbk9hgZncu1aeh3DVnX1ScIHHX8_dy3zFhZCJol6RCYykwIBNDRoCjtYQAvD_BwE&gclsrc=aw.ds',
//     // nintendo_eshop_link='https://www.nintendo.com/games/detail/mario-golf-super-rush-switch/',
//     // is_physical='1',
//     // is_digital='1',
//     // is_dlc='0',
//     // img_self_link='mario-golf-super-rush',
//     // banner_img_self_link='mario-golf-super-rush',
//     // switch_img_self_link='mario-golf-super-rush-switch',
//     // ps5_img_self_link='',
//     // ps4_img_self_link='',
//     // xbox_img_self_link='',
//     // platforms='["Switch"]',
//     // screenshot_self_links='[]',
//     // coverage_links='[]'

//     {
//         game_title: "Pokémon Brilliant Diamond", 
//         release_date: '2021-11-19', 
//         preorder_date:'', 
//         developer:'ILCA',
//         publisher:'Nintendo',
//         hype:'0',
//         msrp:'$59.99',
//         amazon_link:'',
//         target_link:'',
//         nintendo_eshop_link:'',
//         steam_link:'',
//         kickstarter_link:'',
//         is_physical:'1',
//         is_digital:'1',
//         img_self_link: 'https://assets.nintendo.com/image/upload/c_pad,f_auto,h_613,q_auto,w_1089/ncom/en_US/games/switch/p/pokemon-brilliant-diamond-switch/hero?v=2021052619', 
//         banner_img_self_link: 'https://assets.nintendo.com/image/upload/c_pad,f_auto,h_613,q_auto,w_1089/ncom/en_US/games/switch/p/pokemon-brilliant-diamond-switch/hero?v=2021052619',
//         switch_img_self_link: 'https://diamondpearl.pokemon.com/assets/img/global/en-us/packshot-d-2x.png',
//         ps5_img_self_link:'',
//         ps4_img_self_link:'',
//         xbox_img_self_link:'',
//         platforms: ["Switch"],
//         screenshot_self_links:'[]',
//         coverage_links:'[]'
//     },
//     {
//         game_title: "Elden Ring", 
//         release_date: '2022-1-21', 
//         preorder_date:'', 
//         developer:'FromSoftware',
//         publisher:'Bandai Namco',
//         hype:'0',
//         msrp:'$59.99',
//         amazon_link:'',
//         target_link:'',
//         nintendo_eshop_link:'',
//         steam_link:'',
//         kickstarter_link:'',
//         is_physical:'1',
//         is_digital:'1',
//         img_self_link: 'https://assets.nintendo.com/image/upload/c_pad,f_auto,h_613,q_auto,w_1089/ncom/en_US/games/switch/p/pokemon-brilliant-diamond-switch/hero?v=2021052619', 
//         banner_img_self_link: 'https://assets.nintendo.com/image/upload/c_pad,f_auto,h_613,q_auto,w_1089/ncom/en_US/games/switch/p/pokemon-brilliant-diamond-switch/hero?v=2021052619',
//         switch_img_self_link: 'https://diamondpearl.pokemon.com/assets/img/global/en-us/packshot-d-2x.png',
//         ps5_img_self_link:'',
//         ps4_img_self_link:'',
//         xbox_img_self_link:'',
//         platforms: ["PS4", "PS5", "XBO", "XBS"],
//         screenshot_self_links:'[]',
//         coverage_links:'[]'
//     },
//     {
//         game_title: "Sky", 
//         release_date: '2021-6-29', 
//         preorder_date:'', 
//         developer:'',
//         publisher:'',
//         hype:'0',
//         msrp:'',
//         amazon_link:'',
//         target_link:'',
//         nintendo_eshop_link:'',
//         steam_link:'',
//         kickstarter_link:'',
//         is_physical:'1',
//         is_digital:'1',
//         img_self_link: 'https://assets.nintendo.com/image/upload/c_pad,f_auto,h_613,q_auto,w_1089/ncom/en_US/games/switch/p/pokemon-brilliant-diamond-switch/hero?v=2021052619', 
//         banner_img_self_link: 'https://assets.nintendo.com/image/upload/c_pad,f_auto,h_613,q_auto,w_1089/ncom/en_US/games/switch/p/pokemon-brilliant-diamond-switch/hero?v=2021052619',
//         switch_img_self_link: 'https://diamondpearl.pokemon.com/assets/img/global/en-us/packshot-d-2x.png',
//         ps5_img_self_link:'',
//         ps4_img_self_link:'',
//         xbox_img_self_link:'',
//         platforms: ["Switch"],
//         screenshot_self_links:'[]',
//         coverage_links:'[]'
//     },
//     {
//         game_title: "Sable", 
//         release_date: '2021-9-23', 
//         preorder_date:'', 
//         developer:'',
//         publisher:'',
//         hype:'0',
//         msrp:'',
//         amazon_link:'',
//         target_link:'',
//         nintendo_eshop_link:'',
//         steam_link:'',
//         kickstarter_link:'',
//         is_physical:'1',
//         is_digital:'1',
//         img_self_link: 'https://assets.nintendo.com/image/upload/c_pad,f_auto,h_613,q_auto,w_1089/ncom/en_US/games/switch/p/pokemon-brilliant-diamond-switch/hero?v=2021052619', 
//         banner_img_self_link: 'https://assets.nintendo.com/image/upload/c_pad,f_auto,h_613,q_auto,w_1089/ncom/en_US/games/switch/p/pokemon-brilliant-diamond-switch/hero?v=2021052619',
//         switch_img_self_link: 'https://diamondpearl.pokemon.com/assets/img/global/en-us/packshot-d-2x.png',
//         ps5_img_self_link:'',
//         ps4_img_self_link:'',
//         xbox_img_self_link:'',
//         platforms: [""],
//         screenshot_self_links:'[]',
//         coverage_links:'[]'
//     },
//     {
//         game_title: "Pokémon Legend Arceus", 
//         release_date: '2021-11-19', 
//         preorder_date:'', 
//         developer:'Game Freak',
//         publisher:'Nintendo',
//         hype:'0',
//         msrp:'$59.99',
//         amazon_link:'',
//         target_link:'',
//         nintendo_eshop_link:'',
//         steam_link:'',
//         kickstarter_link:'',
//         is_physical:'1',
//         is_digital:'1',
//         img_self_link: 'https://assets.nintendo.com/image/upload/c_pad,f_auto,h_613,q_auto,w_1089/ncom/en_US/games/switch/p/pokemon-brilliant-diamond-switch/hero?v=2021052619', 
//         banner_img_self_link: 'https://assets.nintendo.com/image/upload/c_pad,f_auto,h_613,q_auto,w_1089/ncom/en_US/games/switch/p/pokemon-brilliant-diamond-switch/hero?v=2021052619',
//         switch_img_self_link: 'https://diamondpearl.pokemon.com/assets/img/global/en-us/packshot-d-2x.png',
//         ps5_img_self_link:'',
//         ps4_img_self_link:'',
//         xbox_img_self_link:'',
//         platforms: ["Switch"],
//         screenshot_self_links:'[]',
//         coverage_links:'[]'
//     },
//     {
//         game_title: "Pokémon Legend Arceus", 
//         release_date: '2021-11-19', 
//         preorder_date:'', 
//         developer:'Game Freak',
//         publisher:'Nintendo',
//         hype:'0',
//         msrp:'$59.99',
//         amazon_link:'',
//         target_link:'',
//         nintendo_eshop_link:'',
//         steam_link:'',
//         kickstarter_link:'',
//         is_physical:'1',
//         is_digital:'1',
//         img_self_link: 'https://assets.nintendo.com/image/upload/c_pad,f_auto,h_613,q_auto,w_1089/ncom/en_US/games/switch/p/pokemon-brilliant-diamond-switch/hero?v=2021052619', 
//         banner_img_self_link: 'https://assets.nintendo.com/image/upload/c_pad,f_auto,h_613,q_auto,w_1089/ncom/en_US/games/switch/p/pokemon-brilliant-diamond-switch/hero?v=2021052619',
//         switch_img_self_link: 'https://diamondpearl.pokemon.com/assets/img/global/en-us/packshot-d-2x.png',
//         ps5_img_self_link:'',
//         ps4_img_self_link:'',
//         xbox_img_self_link:'',
//         platforms: ["Switch"],
//         screenshot_self_links:'[]',
//         coverage_links:'[]'
//     },
//     {
//         game_title: "A Little To The Left", 
//         release_date: '2021-10-21', 
//         preorder_date:'', 
//         developer:'Max Inferno',
//         publisher:'Max Inferno',
//         hype:'0',
//         msrp:'',
//         amazon_link:'',
//         target_link:'',
//         nintendo_eshop_link:'',
//         steam_link:'https://store.steampowered.com/app/1629520/A_Little_To_The_Left/',
//         kickstarter_link:'',
//         is_physical:'0',
//         is_digital:'1',
//         img_self_link: 'https://assets.nintendo.com/image/upload/c_pad,f_auto,h_613,q_auto,w_1089/ncom/en_US/games/switch/p/pokemon-brilliant-diamond-switch/hero?v=2021052619', 
//         banner_img_self_link: '',
//         switch_img_self_link: '',
//         ps5_img_self_link:'',
//         ps4_img_self_link:'',
//         xbox_img_self_link:'',
//         platforms: ["Steam"],
//         screenshot_self_links:'[]',
//         coverage_links:'[]'
//     },

// ]